### ISSUE TITLE
Bypassing static constraint with a function

### ISSUE THREAD

**Issue by Kazy** [heathermiller/spores#34]
Inside the body of a spore, every call needs to be static (I don't really understand what that means). In practice, the following piece of code raise the error: `the invocation of 'l.map[List[Int], List[List[Int]]](((elem: Int) => immutable.this.List.apply[Int](elem)))' is not static`.
```scala
    val spNotWorking = spore[List[Int], List[Int]] {
      l => l.map(elem => List(elem)).flatten
    }
```
If instead you create a function doing the same thing, and pass that function inside the spore's header, the error disappear and it works just fine.
```scala
    def f(list: List[Int]): List[Int] = {
      list.map(elem => List(elem)).flatten
    }

    val spWorking = spore[List[Int], List[Int]] {
      val lf = f _
      l => lf(l)
    }
```

Is that a bug or a feature ?

Edit: this happened with Spores 0.2.0.

**Comment by MartinSenne** [comment]
This definitely is a bug.
List[Int] => List[Int] is what the spore does, a function from List to List. So no "external" context, here something outside the capture, is accessed. 
Expected behaviour: This should work smoothly!

**Comment by nimbusgo** [comment]
what's alarming about this is it seems you can get inconsistent results without errors being thrown when you pickle/unplick.

```
    val y = 1
    val f = (x: Int) => x * 2 + y
    val sp = spore{
      val fun = f
      (x:Int) => fun(x)
    }

    val s = JSONPickle(sp.pickle.value).unpickle[Spore[Int, Int]]

```

`sp(2) == 5` while `s(2) == 4`. It seems that it actually changes the function to ignore `y`

**Comment by jvican** [comment]
@nimbusgo That's not the expected way to use a spore. You don't need to reference the function in the spore header. What you're really looking for is to convert from a Function to a Spore, and you get that for free since there's a macro that does the trick. Just cast to `Spore`.

**Comment by jvican** [comment]
BTW, regarding to this issue, the reason why @Kazy has to do that casting is because `f` references to a method, not to a function. I think this is not a bug, mostly because it would happen the same in normal Scala code. But it's something that one must take care when playing around with methods and treating them as functions. I think this issue could be closed since the reported behaviour is the expected one and it's compliant with Scala handles methods vs functions.
