### ISSUE TITLE
Spores don't prevent capture of `this`

### ISSUE THREAD

**Issue by dimbleby** [heathermiller/spores#52]
Hi, 

I saw that you've published a new version - 0.2.4 - so I figured I'd just verify that #43 is fixed as expected.

But it isn't!  My [toy project](https://github.com/dimbleby/spores-experiment) still compiles successfully, in spite of the [bogus capture](https://github.com/dimbleby/spores-experiment/blob/c2f54f7d4127b221225238bd9b4a28867164e4f9/src/main/scala/PingPongTest.scala#L44-L49).

Was I wrong to expect that this ought to be fixed in this release?

**Comment by jvican** [comment]
Yes, sorry but this wasn't fixed in this release.

**Comment by jvican** [comment]
This issue is solved in my branch. This wasn't fun to debug at all for the reasons explained in the commit. Thanks for your patience @dimbleby. I compiled your project and the error is emitted correctly.
